import requests

import Tools
import gosql_v3
import datetime
from subprojects._shared.core.api_credentials import get_credentials


def daily_video_material_report_get(account_id):
    # 获取视频素材维度报表
    start_date = (datetime.datetime.now() - datetime.timedelta(days=30)).strftime("%Y-%m-%d")
    end_date = (datetime.datetime.now() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")
    interface = 'daily_reports/get'
    fields = [
        'date',
        'adgroup_id',
        'account_id',
        'video_id',
        'site_set',
        'adgroup_name',
        'view_count',
        'view_user_count',
        'valid_click_count',
        'click_user_count',
        'cost',
        'acquisition_cost',
        'conversions_count',
        'conversions_cost',
        'deep_conversions_count',
        'conversions_by_display_count',
        'conversions_by_display_cost',
        'conversions_by_click_count',
        'conversions_by_click_rate',
        'conversions_by_click_cost',
        'preview_conversions_count',
        'preview_deep_conversions_count',
        'video_outer_play_count',
        'video_outer_play_user_count',
        'avg_user_play_count',
        'video_outer_play_time_avg_rate',
        'video_outer_play_rate',
        'video_outer_play_cost',
        'video_outer_play10_count',
        'video_outer_play25_count',
        'video_outer_play50_count',
        'video_outer_play75_count',
        'video_outer_play90_count',
        'video_outer_play95_count',
        'video_outer_play100_count',
        'video_outer_play3s_count',
        'video_outer_play5s_count',
        'video_outer_play7s_count',
        'video_inner_play_count',
        'comment_count',
        'praise_count',
        'forward_count',
        'live_stream_crt_click_cnt',
        'effective_leads_count',
        'effect_leads_purchase_count',
        'landing_commodity_detail_exp_pv',
        'app_commodity_page_view_by_display_count',
        'app_commodity_page_view_by_click_count',
        'view_commodity_page_uv',
        'add_wishlist_count',
        'add_cart_pv',
        'add_cart_amount',
        'add_to_cart_price',
        'order_pv',
        'order_uv',
        'order_amount',
        'live_stream_order_pv',
        'live_stream_order_amount',
        'cheout_pv_1d',
        'cheout_fd',
        'cheout_pv_3d',
        'cheout_td',
        'cheout_pv_5d',
        'cheout_5d_cost',
        'cheout_pv_7d',
        'cheout_ow',
        'cheout_tw',
        'purchase_clk_15d_pv',
        'cheout_15d',
        'purchase_clk_30d_pv',
        'cheout_om',
        'video_follow_count',
        'video_play_count',
        'video_heart_count',
        'video_comment_count',
        'channels_share_pla_pv',
        'channels_read_offline_pv',
        'channels_heart_offline_pv',
        'channels_comment_offline_pv',
        'channels_share_offline_pv',
        'channels_fav_offline_pv',
        'video_live_subscribe_count',
        'video_live_exp_count',
        'live_stream_exp_uv',
        'channels_live_exit_pla_duration',
        'video_live_heart_count',
        'video_live_heart_user_count',
        'video_live_comment_count',
        'video_live_comment_user_count',
        'video_live_share_count',
        'video_live_share_user_count',
        'video_live_cick_commodity_count',
        'video_live_click_commodity_user_count',
        'video_live_commodity_bubble_exp_count',
        'live_stream_commodity_bubble_clk_pv',
        'live_stream_commodity_shop_bag_clk_pv',
        'live_stream_commodity_shop_list_exp_pv',
        'live_stream_avg_time',
        'fir_og_conv_auto_acquisition_pv',
        'sec_og_conv_auto_acquisition_pv',
        'purchase_dedup_imp_pv',
        'purchase_dedup_clk_pv',
        'purchase_imp_amount',
        'purchase_clk_amount',
        'purchase_imp_cost',
        'purchase_clk_cost',
        'purchase_imp_roi',
        'order_dedup_imp_pv',
        'order_dedup_clk_pv',
        'order_clk_3d_pv',
        'order_imp_3d_pv',
        'order_clk2_3d_pv',
        'order_clk_3d_amount',
        'order_imp_3d_amount',
        'order_clk2_3d_amount',
        'order_clk_3d_cost',
        'order_imp_3d_cost',
        'order_clk2_3d_cost',
    ]
    parameters = {
        "account_id": account_id,
        "level": "REPORT_LEVEL_MATERIAL_VIDEO",
        "time_line": "REPORTING_TIME",
        "page_size": 100,
        "date_range":
            {
                "start_date": start_date,
                "end_date": end_date
            },
        "group_by": ["date", "video_id", "adgroup_id", "site_set"],
        "fields": fields,
        "page": 1
    }
    report_data = Tools.get_api_data(interface=interface, parameters=parameters, fields=fields)
    gosql_v3.api_to_sql(json_data=report_data, sql_name="api_tencent_ad_report_video_material")


def daily_adgroup_report_get(account_id):
    start_date = (datetime.datetime.now() - datetime.timedelta(days=30)).strftime("%Y-%m-%d")
    end_date = (datetime.datetime.now() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")
    interface = 'daily_reports/get'
    print(start_date, end_date)
    fields = [
        'site_set',
        'date',
        'adgroup_id',
        'account_id',
        'adgroup_name',
        'view_count',
        'view_user_count',
        'valid_click_count',
        'click_user_count',
        'cost',
        'acquisition_cost',
        'conversions_count',
        'conversions_cost',
        'deep_conversions_count',
        'conversions_by_display_count',
        'conversions_by_display_cost',
        'conversions_by_click_count',
        'conversions_by_click_cost',
        'preview_conversions_count',
        'preview_deep_conversions_count',
        'video_outer_play_count',
        'video_outer_play_user_count',
        'avg_user_play_count',
        'video_outer_play_time_avg_rate',
        'video_outer_play_rate',
        'video_outer_play_cost',
        'video_outer_play10_count',
        'video_outer_play25_count',
        'video_outer_play50_count',
        'video_outer_play75_count',
        'video_outer_play90_count',
        'video_outer_play95_count',
        'video_outer_play100_count',
        'video_outer_play3s_count',
        'video_outer_play5s_count',
        'video_outer_play7s_count',
        'video_inner_play_count',
        'comment_count',
        'praise_count',
        'forward_count',
        'live_stream_crt_click_cnt',
        'effective_leads_count',
        'effect_leads_purchase_count',
        'landing_commodity_detail_exp_pv',
        'app_commodity_page_view_by_display_count',
        'app_commodity_page_view_by_click_count',
        'view_commodity_page_uv',
        'add_wishlist_count',
        'add_cart_pv',
        'add_cart_amount',
        'add_to_cart_price',
        'order_pv',
        'order_uv',
        'order_amount',
        'live_stream_order_pv',
        'live_stream_order_amount',
        'cheout_pv_1d',
        'cheout_fd',
        'cheout_pv_3d',
        'cheout_td',
        'cheout_pv_5d',
        'cheout_5d_cost',
        'cheout_pv_7d',
        'cheout_ow',
        'cheout_tw',
        'purchase_clk_15d_pv',
        'cheout_15d',
        'purchase_clk_30d_pv',
        'cheout_om',
        'video_follow_count',
        'video_play_count',
        'video_heart_count',
        'video_comment_count',
        'channels_share_pla_pv',
        'channels_read_offline_pv',
        'channels_heart_offline_pv',
        'channels_comment_offline_pv',
        'channels_share_offline_pv',
        'channels_fav_offline_pv',
        'video_live_subscribe_count',
        'video_live_exp_count',
        'live_stream_exp_uv',
        'channels_live_exit_pla_duration',
        'video_live_heart_count',
        'video_live_heart_user_count',
        'video_live_comment_count',
        'video_live_comment_user_count',
        'video_live_share_count',
        'video_live_share_user_count',
        'video_live_cick_commodity_count',
        'video_live_click_commodity_user_count',
        'video_live_commodity_bubble_exp_count',
        'live_stream_commodity_bubble_clk_pv',
        'live_stream_commodity_shop_bag_clk_pv',
        'live_stream_commodity_shop_list_exp_pv',
        'live_stream_avg_time',
        'fir_og_conv_auto_acquisition_pv',
        'sec_og_conv_auto_acquisition_pv',
        'purchase_dedup_imp_pv',
        'purchase_dedup_clk_pv',
        'purchase_imp_amount',
        'purchase_clk_amount',
        'purchase_imp_cost',
        'purchase_clk_cost',
        'purchase_imp_roi',
        'order_dedup_imp_pv',
        'order_dedup_clk_pv',
        'order_clk_3d_pv',
        'order_imp_3d_pv',
        'order_clk2_3d_pv',
        'order_clk_3d_amount',
        'order_imp_3d_amount',
        'order_clk2_3d_amount',
        'order_clk_3d_cost',
        'order_imp_3d_cost',
        'order_clk2_3d_cost',
    ]
    parameters = {
        "account_id": account_id,
        "level": "REPORT_LEVEL_ADGROUP",
        "time_line": "REPORTING_TIME",
        "page_size": 100,
        "group_by": ["date", "adgroup_id", "site_set"],
        "fields": fields,
        "date_range":
            {
                "start_date": start_date,
                "end_date": end_date
            },
        "page": 1
    }
    report_data = Tools.get_api_data(interface=interface, parameters=parameters, fields=fields)
    gosql_v3.api_to_sql(json_data=report_data, sql_name="api_tencent_ad_report_video_ad_group")


if __name__ == '__main__':
    # 主体： 深圳精准健康食物科技有限公司第一分公司
    Tools.get_business_unit_account()

    for i in Tools.organization_account_relation_get():
        account = i["account_id"]
        print(account)
        daily_adgroup_report_get(account_id=account)
        daily_video_material_report_get(account_id=account)

    requests.get(
        get_credentials("bi_refresh_urls", "ds_w9718fd02685f4c41a6451c2", required=True))
    requests.get(
        get_credentials("bi_refresh_urls", "ds_ndcaede2e16174d718cdfbda", required=True))
    requests.get(
        get_credentials("bi_refresh_urls", "ds_n3efeec729bf54f78ad43336", required=True))
